import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "Octane CSS Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      <body className="">{children}</body>
    </html>
  );
}
